#ifndef OBJECTFINDER_H
#define OBJECTFINDER_H

#include "opencv2/highgui/highgui.hpp"
#include "opencv2/imgproc/imgproc.hpp"
#include <opencv2/video/background_segm.hpp>
#include "ControlWindow.hpp"

using namespace std;
using namespace cv;

class ObjectFinder {

private:

    Mat frameGray;
    int maxBlue;
    int maxRed;
    int maxGreen;
    bool showBalls;

    Mat fgMaskMOG; //fg mask generated by MOG method
	Mat fgMaskMOG2; //fg mask fg mask generated by MOG2 method
	Ptr<BackgroundSubtractor> pMOG; //MOG Background subtractor
	Ptr<BackgroundSubtractor> pMOG2; //MOG2 Background subtractor

	ControlWindow controlWindow;

    // Hough Circles Parameters
    int cannyThreshold;
    int accumulatorThreshold;
    int minCircleSize;
    int maxCircleSize;
    int distanceBetweenCircleCenters;
    int dp;

    // inRange Parameters
    int minSaturation;
    int maxSaturation;
    int minValue;
    int maxValue;
    int minHue;
    int maxHue;

    void updateControlVariables();

public:
    ObjectFinder();
    vector<Vec3f> getCircles(Mat frame);
    void findMostFrequentColor (Mat frame) ;
    Mat segmentTable (Mat frame);
    vector<Vec3f> findWhiteBall(Mat frame);
    void backgroundSubtract(Mat frame);
    void processFrame(Mat frame);
};

#endif // OBJECTFINDER_H
